### ISSUE TITLE
Request not issue: Add bgp neighbor on a node/appliance

### ISSUE THREAD

**Issue by Devraj004** [grelleum/SteelConnection#36]
Hi Grelleum,
I am using SteelConnection  for most of  my SCM related work. Thank you for your effort and helping us. 
I am trying to create a script for adding BGP neighbor on a new site appliance.  but didn't find any API for the same.

Please confirm if there any way with steelconnection or  we need to add bgp neighbor manually  on the appliance?

Kind Regards
Devraj

**Comment by grelleum** [comment]
Excellent - that's great to hear that you are making use of SteelConnection!

The Rest API supports adding BGP neighbors for you appliances.  It is documented here:
[AddBGPneighbor](https://support.riverbed.com/apis/scm_beta/scm-2.11.0/scm.config/index.html#!/bgpneigh/post_org_orgid_bgpneighs)

You will need to get the org_id and node_id prior to adding the neighbor.

Here is some sample code to get it working:
```
org_id = sc.lookup.org('CheeseShoppe').get('id')
node_id = sc.lookup.node('XN27746DAE6400B3').get('id')

neighbor = {
    "org": org_id,
    "node": node_id,
    "name": "RouterX",
    "ipv4": "1.2.3.4",
    "remote_as": 65123,
}

result = sc.post(f"/org/{org_id}/bgpneighs", neighbor)  # python 3.6+ syntax
```

Note that the last line uses the f-string syntax that was added in Python 3.6.  That line could be replaced with:
```
result = sc.post("/org/{}/bgpneighs".format(org_id), neighbor)   # older Python releases
```

Let me know if this works for you.

**Comment by Devraj004** [comment]
First of my apologies for not responding back to on this. This is really Excellent Sir! , Awesome Thank you so much. I have also identified that we can achieve the same with uplink option as well. Here is an example.

sc = steelconnection.SConnect(scm_name)

 org_id = sc.lookup.org(org_name)['id']

print('org_id =', org_id)
site = sc.lookup.site(site_code, orgid= org_id)
print("site_id", site["id"])

# Set uplink BGP parameters.
uplink['bgp_router_id'] = '1.2.3.4'
 uplink['bgp_neigh_password'] = 'xxxxx'
 uplink['bgp_neigh_remote_as'] = '65123'
uplink['bgp_neigh_name'] = 'MPLS-PE'
uplink['bgp_local_as'] = '65234'
uplink['bgp_neigh_ipv4'] = '1.2.3.5'

# Upload modified object to the SCM.

 result = sc.put(uplink_mpls, data=uplink)
 print(result)

Please confirm if this also looks ok to you.

Many thanks once again.
